### PR TITLE
Typefor connection

### PR DESCRIPTION
**Pull request by Carolien989**

### CODE REVIEW

**Comment by bbusagroningen** [comment]
@Carolien989 you got a travis error, please fix it and re commit

**Comment by Carolien989** [comment]
I see:  Blueprint
    1) "before all" hook: Should get other branches

But im not sure what this error means? it is something in the last commit with changing the ui select

**Comment by bbusagroningen** [comment]
Well, I think the problem is not there, but rather here: /

home/travis/build/lauraBaakman/2017-Switch-Board-API-Front-End/Switchboard/public/app/components/connections/NewLinkedAPIModalController.js
  116:1  error  Line 116 exceeds the maximum line length of 80  max-len

**Comment by Carolien989** [comment]
Oh wauw thanks! indeed i totally have forgotten to run eslint for the second commit. Thanks!

**Comment by Carolien989** [comment]
@bbusagroningen  Can you review it again?

**Pull request merged**
